#!/bin/bash

set -euf -o pipefail

version="$1"
distro="$2"

cd `dirname "$0"`; cd ..

scripts/install-dependencies

# ---------- clean build

cargo clean
(cd libaptc && make clean)
cargo build --release

# ---------- create package

rm -rf "dist/wbs-monitoring-$version-$distro"
mkdir -p "dist/wbs-monitoring-$version-$distro"

(

	cd "target/release"

	find "." \
		-mindepth 1 \
		-maxdepth 1 \
		-type f \
		-executable

) | while read file; do

	cp "target/release/$file" "dist/wbs-monitoring-$version-$distro/$file"

done

# ----------- create archive

tar \
	--create \
	--xz \
	--file "dist/wbs-monitoring-$version-$distro.tar.xz" \
	--directory "dist" \
	"wbs-monitoring-$version-$distro"

# ex: noet ts=4 filetype=sh
