#!/bin/bash

set -euf -o pipefail

version="$1"

trusty_container="mufasa-trusty"
trusty_root="/var/lib/lxc/$trusty_container/rootfs"
trusty_project="$trusty_root/home/ubuntu/wbs-monitoring"

# ---------- check the version number

if test -f ".git/refs/tags/$version"; then
	echo "Version $version already exists"
	false
fi

# ---------- update the version number

sed_script="/tmp/sed-script-$$"

cat >"$sed_script" <<-END
	/^\[package\]$/, /^\[/ {
		s/version = ".*"/version = "$version\"/
	}
END

sed --in-place \
	--regexp-extended \
	--file "$sed_script" \
	"Cargo.toml"

rm "$sed_script"

# ---------- clean and sync

cargo clean
(cd libaptc && make clean)

sudo rsync \
	--archive \
	--delete \
	--exclude "/.git" \
	--exclude "/dist" \
	--exclude "/target" \
	--exclude "/temp" \
	--exclude "/work" \
	"./" \
	"$trusty_project/"

# ---------- build packages

scripts/build-package "$version" "xenial"

sudo lxc-attach --name "$trusty_container" -- \
sudo -H -u ubuntu \
bash -c "/home/ubuntu/wbs-monitoring/scripts/build-package $version trusty"

sudo rsync \
	--archive \
	"$trusty_project/dist/" \
	"dist/"

# ---------- git commit

git reset "HEAD"
git add "Cargo.toml" "Cargo.lock"
git commit --message "release $version"
git stash --include-untracked

# ---------- upload to server

scp "dist/wbs-monitoring-$version-xenial.tar.xz" "dist:dist/wbs-monitoring/"
scp "dist/wbs-monitoring-$version-trusty.tar.xz" "dist:dist/wbs-monitoring/"

# ---------- create tag

git tag "$version"
git push origin master --tags

# ex: noet ts=4 filetype=sh
