#!/bin/bash

packages=(
	"build-essential"
	"cmake"
	"libapt-pkg-dev"
	"libssl-dev"
	"pkg-config"
)

sudo apt install "${packages[@]}"

if ! (
	rustc --version \
	| egrep '^rustc 1.13.0 '
); then

	rm -rf "rust-1.13.0-x86_64-unknown-linux-gnu.tar.gz"
	wget "https://static.rust-lang.org/dist/rust-1.13.0-x86_64-unknown-linux-gnu.tar.gz"

	rm -rf "rust-1.13.0-x86_64-unknown-linux-gnu"
	tar xzf "rust-1.13.0-x86_64-unknown-linux-gnu.tar.gz"

	cd "rust-1.13.0-x86_64-unknown-linux-gnu"
	./install.sh

fi

# ex: noet ts=4 filetype=sh
