#!/usr/bin/env php
<?php
include("/etc/php5/nagios_plugin_output.php");

require '/etc/php5/robot-client/RobotClient.class.php';

$plugin_output = new nagios_plugin_output();

if (count ($argv) != 7) {
	$output = $plugin_output->unknown("USAGE: check_hetzner -i <server-ip> -u <hetzner-username> -p <password>.");
	echo($output['msg']);
	exit($output['state']);
}

$server_ip = "";
$login = "";
$password = "";

$argIndex = 1;
while ($argIndex < 7) {
	if ($argv[$argIndex] == "--ip") {
		$argIndex++;
		$server_ip = $argv[$argIndex];
	}
	elseif ($argv[$argIndex] == "--username") {
		$argIndex++;
		$login = $argv[$argIndex];
	}
	elseif ($argv[$argIndex] == "--password") {
		$argIndex++;
		$password = $argv[$argIndex];
	}
	else {
		$output = $plugin_output->unknown("USAGE: check_hetzner -i <server-ip> -u <hetzner-username> -p <password>.");
		echo($output['msg']);
		exit($output['state']);
	}
	$argIndex++;
}

// retrieve the server info

$robot = new RobotClient('https://robot-ws.your-server.de', $login, $password);

// check if the server bandwith is throttled

$server = $robot->serverGet($server_ip);

$bandwidth_throttled = $server->server->throttled;


$throttled = "";
if (!$bandwidth_throttled) {
	$throttled = "Bandwidth-OK: Bandwidth not throttled.\n";
}
else {
	$throttled = "Bandwidth-CRITICAL: Bandwidth throttled!\n";
}

// check whether the ip is locked

$ip = $robot->ipGet($server_ip);

$ip_locked = $ip->ip->locked;

$locked = "";
if (!$ip_locked) {
	$locked = "Locked-OK: $server_ip not locked.\n";
}
else {
	$locked = "Locked-CRITICAL: $server_ip locked!\n";
}

// output

if ($ip_locked) {
	$output = $plugin_output->critical($locked.$throttled);
}
elseif ($bandwidth_throttled) {
	$output = $plugin_output->critical($throttled.$locked.$payment);
}
elseif (!$ip_locked and !$bandwidth_throttled) {
	$output = $plugin_output->ok($locked.$throttled);
}
else {
	$output = $plugin_output->unknown("Could not perform the check correctly.");
}

echo($output['msg']);
exit($output['state']);

?>
